/**
 * Passport trust language — the ONLY wording the Passport may use about itself.
 *
 * The Skill Passport is an internal learning record computed from the learner's
 * own activity in Xpedition. There is no signing key, no issuer, no external
 * verifier and no proctoring. It must never be presented as a cryptographic,
 * verified, proctored or externally endorsed credential.
 */

export const PASSPORT_TITLE = 'Skill Passport';
export const PASSPORT_RECORD_BADGE = 'Learning Record';
export const PASSPORT_DISCLAIMER =
  'Internal learning record generated by Xpedition from your own activity. It is not an externally verified, proctored or cryptographically signed credential.';
export const PASSPORT_SHARE_FOOTER = 'Xpedition learning record · self-generated · not externally verified';
export const PASSPORT_PUBLIC_UNAVAILABLE =
  'This Skill Passport link is not available. Xpedition Passports are private learning records; public publishing and external verification are not offered yet.';

/**
 * Claims that must never appear in Passport UI copy unless a real credential
 * system (issuer, signature, verification endpoint) exists. Used by tests.
 */
export const UNSUPPORTED_CREDENTIAL_CLAIMS: RegExp[] = [
  /cryptograph/i,
  /verified\s+(skill\s+)?(passport|credential|competenc)/i,
  /verified\s+passport/i,
  /credential\s+id/i,
  /proctored/i,
  /proof\s+of\s+competence/i,
  /\bauthenticated\b(?!\s+(user|session|learner|request|administrator|admin))/i,
  /blockchain/i,
  /tamper[-\s]?proof/i,
  /verified\s+by\s+(google|microsoft|xpedition)/i,
  /verification\s+system/i,
  /verified\s+(hands-on|solo|concept|via)/i,
];

/**
 * Explicit negations ("It is not an externally verified, proctored or
 * cryptographically signed credential.") are honest disclaimers, not claims.
 * Only a clause that starts with "not" and names the credential terms is
 * removed before scanning; any positive claim elsewhere is still caught.
 */
const NEGATED_CLAIM_CLAUSE =
  /\bnot\s+(?:an?\s+)?(?:externally\s+)?(?:verified|proctored|cryptographically|signed)[^.]*/gi;

export function findUnsupportedClaims(text: string): string[] {
  const affirmative = text.replace(NEGATED_CLAIM_CLAUSE, ' ');
  return UNSUPPORTED_CREDENTIAL_CLAIMS.filter((re) => re.test(affirmative)).map((re) => re.source);
}
