import { jsPDF } from 'jspdf';

interface ChunkItem {
  say: string;
  code?: string;
}

interface PdfOptions {
  conceptName: string;
  chunks: ChunkItem[];
  dateStr?: string;
}

export function downloadNotesPdf({ conceptName, chunks, dateStr }: PdfOptions) {
  const doc = new jsPDF();
  const date = dateStr || new Date().toISOString().split('T')[0];
  const sanitizeName = conceptName.toLowerCase().replace(/[^a-z0-9]/g, '-');

  // Title Header
  doc.setFontSize(20);
  doc.setTextColor(20, 30, 25);
  doc.text(conceptName, 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`XPedition Lesson Notes · ${date}`, 14, 27);
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 30, 196, 30);

  let y = 38;

  chunks.forEach((chk, idx) => {
    // Check page space
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(33, 150, 243);
    doc.text(`Topic ${idx + 1}`, 14, y);
    y += 6;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);

    const splitText = doc.splitTextToSize(chk.say, 180);
    doc.text(splitText, 14, y);
    y += splitText.length * 5 + 4;

    if (chk.code) {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      doc.setFont('courier', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      const codeLines = doc.splitTextToSize(chk.code, 170);
      doc.rect(14, y - 4, 180, codeLines.length * 4 + 6, 'F');
      doc.text(codeLines, 18, y + 1);
      y += codeLines.length * 4 + 10;
    }
  });

  // Footer
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by XPedition', 14, 285);
    doc.text(`Page ${i} of ${totalPages}`, 180, 285);
  }

  doc.save(`xpedition-notes-${sanitizeName}-${date}.pdf`);
}

export function downloadFlashcardsPdf({ conceptName, chunks, dateStr }: PdfOptions) {
  const doc = new jsPDF();
  const date = dateStr || new Date().toISOString().split('T')[0];
  const sanitizeName = conceptName.toLowerCase().replace(/[^a-z0-9]/g, '-');

  chunks.forEach((chk, idx) => {
    if (idx > 0) doc.addPage();

    // Border Card Frame
    doc.setDrawColor(33, 150, 243);
    doc.setLineWidth(1);
    doc.roundedRect(15, 20, 180, 250, 6, 6);

    // Front Header
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(33, 150, 243);
    doc.text(`FLASHCARD ${idx + 1} of ${chunks.length} — FRONT`, 105, 35, { align: 'center' });

    doc.setFontSize(16);
    doc.setTextColor(20, 20, 20);
    doc.text(`What is key takeaway #${idx + 1} of ${conceptName}?`, 105, 60, { align: 'center', maxWidth: 160 });

    doc.setDrawColor(220, 220, 220);
    doc.line(30, 130, 180, 130);

    // Back Header
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(76, 175, 80);
    doc.text(`BACK — EXPLANATION`, 105, 145, { align: 'center' });

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);
    const splitExplanation = doc.splitTextToSize(chk.say, 160);
    doc.text(splitExplanation, 105, 165, { align: 'center' });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by XPedition', 105, 260, { align: 'center' });
  });

  doc.save(`xpedition-flashcards-${sanitizeName}-${date}.pdf`);
}
