import type { ClassroomLesson } from '@/components/classroom/types';
export const NEURAL_NETWORK_BASICS_LESSON: ClassroomLesson = {
 id:'lesson_neural_network_m1_m12',conceptId:'neural_network_basics',topicTitle:'Neural Networks: From One Neuron to Language Models',subject:'Artificial Intelligence',category:'Neural Networks',gradeLevel:'High School / Undergraduate / Beginner AI',estimatedMinutes:45,hasFormulas:true,
 definition:'A neural network is a mathematical model that transforms inputs through layers of weighted computations to produce an output.',
 learningObjective:'Build an intuition for neural networks through ten visual topics, then prove understanding with a final decision-tree assessment.',
 steps:[
 {id:'m1_single_neuron',stepNumber:1,stage:'explain',title:'M1 · One Neuron',subtitle:'Input → Weighted Sum → Activation → Output',buddyDialogue:'Start tiny. A neuron takes inputs, multiplies them by weights, adds a bias, then passes the result through an activation function.',buddyState:'EXPLAINING',boardTitle:'Watch One Neuron Calculate',boardSummary:'Two inputs enter one neuron. Follow every number as the signal becomes a prediction.',keyPrinciple:'Weights control influence, bias shifts the pre-activation, and the activation function converts it into the neuron output.',visualType:'interactive_simulation',visualData:{neuralMode:'m1'},tryThis:'Trace x₁ and x₂ into the weighted sum and predict whether increasing a weight will raise the output.'},
 {id:'m2_activation',stepNumber:2,stage:'show',title:'M2 · Activation Functions',subtitle:'Shape the signal',buddyDialogue:'The weighted sum is not the final answer. Activation functions shape the signal so a network can learn useful non-linear patterns.',buddyState:'EXPLAINING',boardTitle:'From Raw Signal to Useful Signal',boardSummary:'Compare sigmoid, ReLU and tanh and see how the same input can be transformed in different ways.',keyPrinciple:'Non-linear activations let stacked layers represent patterns that a purely linear network could not.',visualType:'interactive_simulation',visualData:{neuralMode:'m2'},tryThis:'Compare the range and shape of sigmoid, ReLU and tanh before moving on.'},
 {id:'m3_forward',stepNumber:3,stage:'show',title:'M3 · Forward Propagation',subtitle:'Layer by layer',buddyDialogue:'Now connect neurons. A forward pass feeds each layer with the previous layer’s output until the network produces a prediction.',buddyState:'EXPLAINING',boardTitle:'Follow the Signal Through a Network',boardSummary:'Watch a 2 → 3 → 1 network transform the input into a final prediction.',keyPrinciple:'Forward propagation applies the learned transformation of each layer in order.',visualType:'interactive_simulation',visualData:{neuralMode:'m3'},tryThis:'Run the forward pass and trace one signal from an input node to the output.'},
 {id:'m4_loss',stepNumber:4,stage:'show',title:'M4 · Loss Functions',subtitle:'Measure the miss',buddyDialogue:'A prediction is only useful if we can measure how far it is from the target. Loss turns that difference into a number the network can learn from.',buddyState:'EXPLAINING',boardTitle:'Prediction vs Target',boardSummary:'Compare the model prediction with the target and see how the loss quantifies the error.',keyPrinciple:'Training needs a differentiable objective that tells the model how wrong its prediction is.',visualType:'interactive_simulation',visualData:{neuralMode:'m4'},tryThis:'Look at the prediction, target and loss meter. Which direction would reduce the loss?'},
 {id:'m5_backprop',stepNumber:5,stage:'show',title:'M5 · Backpropagation',subtitle:'Send the error backward',buddyDialogue:'The network now sends the error signal backward. Gradients tell each parameter how much it contributed to the loss.',buddyState:'EXPLAINING',boardTitle:'The Error Travels Backward',boardSummary:'See the same network light up in reverse as gradients move from the output toward earlier weights.',keyPrinciple:'Backpropagation efficiently applies the chain rule to compute gradients for many parameters.',visualType:'interactive_simulation',visualData:{neuralMode:'m5'},tryThis:'Follow the reverse path and identify where the output error reaches the hidden layer.'},
 {id:'m6_gradient',stepNumber:6,stage:'practice',title:'M6 · Gradient Descent',subtitle:'Tune the weights',buddyDialogue:'A gradient points toward increasing loss. Gradient descent moves parameters in the opposite direction so the loss comes down.',buddyState:'ENCOURAGING',boardTitle:'Step Down the Loss Landscape',boardSummary:'Visualize parameter updates as a point moving toward a lower-loss region.',keyPrinciple:'θ ← θ − η∂L/∂θ: the learning rate controls how large each update is.',visualType:'interactive_simulation',visualData:{neuralMode:'m6'},tryThis:'Run an update and watch the parameter move toward lower loss.'},
 {id:'m7_deep',stepNumber:7,stage:'show',title:'M7 · Deep Networks',subtitle:'Stack learned representations',buddyDialogue:'Add more hidden layers and the network can build increasingly rich representations: simple patterns first, then combinations of those patterns.',buddyState:'EXPLAINING',boardTitle:'Why Depth Matters',boardSummary:'Compare a shallow network with deeper stacks of learned transformations.',keyPrinciple:'Depth creates successive representations rather than simply adding more isolated neurons.',visualType:'interactive_simulation',visualData:{neuralMode:'m7'},tryThis:'Add a hidden layer and notice how another transformation appears between input and output.'},
 {id:'m8_attention',stepNumber:8,stage:'show',title:'M8 · Self-Attention',subtitle:'Let tokens use context',buddyDialogue:'Attention lets one token compare itself with other tokens and assign more weight to the information that matters for its current context.',buddyState:'EXPLAINING',boardTitle:'Watch Attention Connect Tokens',boardSummary:'Select a token and inspect the query, key, value and softmax idea behind its context mix.',keyPrinciple:'Attention weights come from query-key similarity and are used to mix value information.',visualType:'interactive_simulation',visualData:{neuralMode:'m8'},tryThis:'Select different tokens and watch the context relationship change.'},
 {id:'m9_heads_position',stepNumber:9,stage:'show',title:'M9 · Multiple Heads + Position',subtitle:'Relationships and order',buddyDialogue:'Different attention heads can inspect different relationships. Positional encoding adds information about where each token sits in the sequence.',buddyState:'EXPLAINING',boardTitle:'Two Views of Context + Token Order',boardSummary:'Compare two attention heads, then change the position vector to see why order must be represented.',keyPrinciple:'Multi-head attention combines several attention patterns while positional information exposes sequence order.',visualType:'interactive_simulation',visualData:{neuralMode:'m9'},tryThis:'Switch positions and compare the positional vector added to each token.'},
 {id:'m10_transformer',stepNumber:10,stage:'practice',title:'M10 · Transformer Block',subtitle:'Attention → Residual → Norm → FFN',buddyDialogue:'We can now assemble the block: attention mixes context, residuals preserve the information stream, normalization stabilizes values, and the feed-forward network transforms each position.',buddyState:'EXPLAINING',boardTitle:'Inside One Transformer Block',boardSummary:'Step through the operations that turn a contextual representation into a refined representation.',keyPrinciple:'A transformer block is a sequence of tensor transformations, not a black box.',visualType:'interactive_simulation',visualData:{neuralMode:'m10'},tryThis:'Read the block from left to right and name what each operation contributes.'},
 {id:'q1_final_check',stepNumber:11,stage:'challenge',title:'Q1 · Decision Check',subtitle:'Prove the ideas connect',buddyDialogue:'You have seen the full path. Now prove you can connect the pieces without another teaching prompt.',buddyState:'THINKING',boardTitle:'Final Check · What makes a network learn?',boardSummary:'Use the decision tree and choose the statement that best connects parameters, loss and gradients.',keyPrinciple:'A neural network learns by changing parameters to reduce an objective using gradients.',visualType:'interactive_simulation',visualData:{neuralMode:'q1'},checkQuestion:{id:'nn_final_check_1',prompt:'Which chain best describes how a neural network learns from an example?',options:[{id:'learn',text:'Predict → measure loss → backpropagate gradients → update weights',isCorrect:true,feedback:'Correct. The forward pass makes the prediction, loss measures error, backprop computes gradients, and the update changes parameters.'},{id:'random',text:'Randomly change weights until the output looks right',isCorrect:false,feedback:'Training uses gradients and a defined objective rather than random weight changes.'},{id:'reverse',text:'Update weights first, then calculate the prediction',isCorrect:false,feedback:'The prediction and loss come before the gradient-based update.'}]}},
 {id:'q2_mastery_path',stepNumber:12,stage:'challenge',title:'Q2 · Mastery Path',subtitle:'Choose the next neural-network idea',buddyDialogue:'One last decision. Your answer here becomes the signal for where the next neural-network lesson should go.',buddyState:'THINKING',boardTitle:'Decision Tree · Choose Your Next Path',boardSummary:'Connect your strongest understanding to the next visual topic: neuron mechanics, attention, or optimization.',keyPrinciple:'Your next topic should build directly on the idea you can explain and use.',visualType:'interactive_simulation',visualData:{neuralMode:'q2'},checkQuestion:{id:'nn_final_check_2',prompt:'Which topic do you want to deepen next?',options:[{id:'neuron_path',text:'Neuron mechanics and activations',isCorrect:true,feedback:'Great. The next path can deepen the computation inside a neuron.'},{id:'attention_path',text:'Attention and transformer internals',isCorrect:true,feedback:'Great. The next path can deepen context mixing and transformer internals.'},{id:'optimization_path',text:'Loss, gradients and optimization',isCorrect:true,feedback:'Great. The next path can deepen how training changes parameters.'}]}}
 ],
 questions:[],flashcards:[],sources:[
 {id:'nn_src_1',title:'Deep Learning',authorOrPublisher:'Goodfellow, Bengio & Courville',type:'textbook',note:'Reference for neural networks and deep learning.'},
 {id:'nn_src_2',title:'Attention Is All You Need',authorOrPublisher:'Vaswani et al.',type:'paper',url:'https://arxiv.org/abs/1706.03762',note:'Reference for self-attention and positional encoding.'}
 ],
 buddyScript:{introduction:'We will build the idea from one neuron to token prediction, one calculation at a time.',correct:'Correct. Keep following the numbers.',incorrect:'Not quite. Trace the current operation on the Smart Board.',hint:'Inspect the highlighted calculation on the board.',transition:'Good. Move to the next transformation.',completion:'You traced the full path from a neuron to token prediction.'},
 xiraPrompts:{why:'Explain why this neural-network step works.',simpler:'Explain the current neural-network operation more simply.',example:'Give a concrete numerical example for this step.',hint:'Give me one small hint without revealing the answer.',deeper:'Connect this step to modern AI systems.'}
};