import type { ClassroomLesson } from '@/components/classroom/types';
export const NEURAL_NETWORK_BASICS_LESSON: ClassroomLesson = {
 id:'lesson_neural_network_m1_m9',conceptId:'neural_network_basics',topicTitle:'Neural Networks: From One Neuron to Language Models',subject:'Artificial Intelligence',category:'Neural Networks',gradeLevel:'High School / Undergraduate / Beginner AI',estimatedMinutes:35,hasFormulas:true,
 definition:'A neural network is a mathematical model that transforms inputs through layers of weighted computations to produce an output.',
 learningObjective:'Build an intuition for neural networks by calculating a neuron, forwarding through layers, learning with backpropagation, understanding attention and transformer blocks, and tracing next-token prediction.',
 steps:[
 {id:'m1_single_neuron',stepNumber:1,stage:'explain',title:'M1 · One Neuron',subtitle:'Input → Weighted Sum → Activation → Output',buddyDialogue:'Start tiny. A neuron takes inputs, multiplies them by weights, adds a bias, then passes the result through an activation function.',buddyState:'EXPLAINING',boardTitle:'Watch One Neuron Calculate',boardSummary:'Two inputs enter one neuron. Every number is deterministic so you can follow the calculation exactly.',keyPrinciple:'Weights control influence, bias shifts the activation, and the activation function converts the pre-activation into the neuron output.',visualType:'interactive_simulation',visualData:{neuralMode:'m1'},tryThis:'Change an input or weight and predict whether the output rises or falls.'},
 {id:'m2_interact',stepNumber:2,stage:'interact',title:'M2 · Change It, Predict It',subtitle:'The learner controls the neuron',buddyDialogue:'Now you drive the neuron. Move the sliders, predict what should happen, then run the calculation and compare.',buddyState:'ENCOURAGING',boardTitle:'Change Inputs, Weights and Bias',boardSummary:'The same deterministic neuron updates live as you change its parameters.',keyPrinciple:'A parameter changes the calculation immediately; the network has no hidden randomness.',visualType:'interactive_simulation',visualData:{neuralMode:'m2'},tryThis:'Make the output cross 0.75 using the controls.'},
 {id:'m3_network',stepNumber:3,stage:'show',title:'M3 · Build a Small Network',subtitle:'Input Layer → Hidden Layer → Output',buddyDialogue:'We connect three hidden neurons to two inputs, then combine them into one output.',buddyState:'EXPLAINING',boardTitle:'A 2 → 3 → 1 Network',boardSummary:'The hidden layer creates three intermediate representations before the output neuron combines them.',keyPrinciple:'Forward propagation means applying each layer in order using outputs from the previous layer.',visualType:'interactive_simulation',visualData:{neuralMode:'m3'},tryThis:'Inspect one hidden neuron and trace its two incoming weights.'},
 {id:'m4_backprop',stepNumber:4,stage:'practice',title:'M4 · How the Network Learns',subtitle:'Loss → Backpropagation → Weight Update',buddyDialogue:'The network compares its prediction with a target, measures loss, sends gradients backward, and nudges weights.',buddyState:'THINKING',boardTitle:'One Real Training Step',boardSummary:'Target = 1 and learning rate = 0.5. Calculate loss, gradients and updated parameters.',keyPrinciple:'Gradient descent changes parameters in the direction that reduces the loss.',visualType:'interactive_simulation',visualData:{neuralMode:'m4'},tryThis:'Run one training step, then run forward again and observe the new prediction.'},
 {id:'m5_deep',stepNumber:5,stage:'show',title:'M5 · Why Deep Learning?',subtitle:'Stack more hidden layers',buddyDialogue:'Add hidden layers and the representation becomes deeper. Each layer transforms what the previous layer discovered.',buddyState:'EXPLAINING',boardTitle:'Shallow vs Deep',boardSummary:'Compare one to four hidden layers using deterministic weights.',keyPrinciple:'Depth means successive learned transformations, not simply a bigger diagram.',visualType:'interactive_simulation',visualData:{neuralMode:'m5'},tryThis:'Add a hidden layer and watch another transformation appear.'},
 {id:'m6_attention',stepNumber:6,stage:'practice',title:'M6 · Watch Attention Think',subtitle:'Query → Keys → Values → Softmax → Output',buddyDialogue:'Attention lets one token compare itself with every other token and assign weights to the information it should use.',buddyState:'EXPLAINING',boardTitle:'Self-Attention on “the cat sat”',boardSummary:'Select a query token and inspect its similarities, softmax weights and weighted value output.',keyPrinciple:'Attention weights come from query-key similarity and are used to mix value vectors.',visualType:'interactive_simulation',visualData:{neuralMode:'m6'},tryThis:'Select “sat” and identify which token receives the largest attention weight.'},
 {id:'m7_multihead',stepNumber:7,stage:'show',title:'M7 · Multi-Head Attention + Position',subtitle:'Parallel relationships + token order',buddyDialogue:'Multiple heads can inspect different relationships, while positional encoding tells the model where each token sits.',buddyState:'EXPLAINING',boardTitle:'Two Heads, Then Add Position',boardSummary:'Run two deterministic attention heads, concatenate their outputs, project them, then add sinusoidal positional encoding.',keyPrinciple:'Multi-head attention combines several attention patterns; positional encoding makes token order available.',visualType:'interactive_simulation',visualData:{neuralMode:'m7'},tryThis:'Compare positional vectors for “the cat sat” and “sat the cat”.'},
 {id:'m8_transformer',stepNumber:8,stage:'practice',title:'M8 · Transformer Block + Next Token',subtitle:'Attention → Residual → Norm → FFN → prediction',buddyDialogue:'We assemble the transformer block, then use its final representation to score possible next tokens.',buddyState:'EXPLAINING',boardTitle:'From Context to the Next Token',boardSummary:'Step through the transformer block, then follow the final representation into a next-token prediction.',keyPrinciple:'A transformer block refines contextual representations; a language-model head converts the final representation into a probability distribution over next tokens.',visualType:'interactive_simulation',visualData:{neuralMode:'m8'},tryThis:'Step through the block, then predict which token should receive the highest probability.'},
 {id:'m9_prediction',stepNumber:9,stage:'challenge',title:'M9 · From Transformer to Token Prediction',subtitle:'Context → logits → probabilities → next token',buddyDialogue:'A language model turns a final representation into vocabulary scores, probabilities and a next-token choice. This is a tiny teaching model, not a trained LLM.',buddyState:'THINKING',boardTitle:'Final Check · Choose the Learning Path',boardSummary:'Use the decision tree, answer the check, and your result becomes the signal for the next neural-network topic.',keyPrinciple:'A neural network learns by predicting, measuring loss, computing gradients, and updating parameters; transformer-style attention builds context for prediction.',visualType:'interactive_simulation',visualData:{neuralMode:'q1'},checkQuestion:{id:'nn_final_check',prompt:'Which sequence best connects the ideas taught in this class?',options:[{id:'correct',text:'Forward prediction → loss → backprop gradients → update weights → attention builds context',isCorrect:true,feedback:'Correct. You connected the training loop with the contextual representation used by transformer-style models.'},{id:'wrong1',text:'Randomly change weights → choose a token → calculate loss afterward',isCorrect:false,feedback:'Training is driven by a defined loss and gradients, not random weight changes.'},{id:'wrong2',text:'Attention happens first → weights never change → prediction is fixed',isCorrect:false,feedback:'Attention is part of the forward computation; learning still updates parameters from gradients.'}]},tryThis:'Use the decision tree first, then commit to your answer.'}
 ],
 questions:[],flashcards:[],sources:[
 {id:'nn_src_1',title:'Deep Learning',authorOrPublisher:'Goodfellow, Bengio & Courville',type:'textbook',note:'Reference for neural networks and deep learning.'},
 {id:'nn_src_2',title:'Attention Is All You Need',authorOrPublisher:'Vaswani et al.',type:'paper',url:'https://arxiv.org/abs/1706.03762',note:'Reference for self-attention and positional encoding.'}
 ],
 buddyScript:{introduction:'We will build the idea from one neuron to token prediction, one calculation at a time.',correct:'Correct. Keep following the numbers.',incorrect:'Not quite. Trace the current operation on the Smart Board.',hint:'Inspect the highlighted calculation on the board.',transition:'Good. Move to the next transformation.',completion:'You traced the full path from a neuron to token prediction.'},
 xiraPrompts:{why:'Explain why this neural-network step works.',simpler:'Explain the current neural-network operation more simply.',example:'Give a concrete numerical example for this step.',hint:'Give me one small hint without revealing the answer.',deeper:'Connect this step to modern AI systems.'}
};