import type { ClassroomLesson } from '@/components/classroom/types';
export const NEURAL_NETWORK_BASICS_LESSON: ClassroomLesson = {
 id:'lesson_neural_network_m1_m9',conceptId:'neural_network_basics',topicTitle:'Neural Networks: From One Neuron to Language Models',subject:'Artificial Intelligence',category:'Neural Networks',gradeLevel:'High School / Undergraduate / Beginner AI',estimatedMinutes:35,hasFormulas:true,
 definition:'A neural network is a mathematical model that transforms inputs through layers of weighted computations to produce an output.',
 learningObjective:'Build an intuition for neural networks by calculating a neuron, forwarding through layers, learning with backpropagation, understanding attention and transformer blocks, and tracing next-token prediction.',
 steps:[
 {id:'m1_single_neuron',stepNumber:1,stage:'explain',title:'M1 · One Neuron + Activation',subtitle:'Weighted sum → activation → output',buddyDialogue:'Start tiny. A neuron combines inputs with weights and bias, then an activation function turns that signal into an output.',buddyState:'EXPLAINING',boardTitle:'Inside One Neuron',boardSummary:'See the weighted sum and the activation that turns it into a prediction.',keyPrinciple:'Weights control influence, bias shifts the pre-activation, and a non-linear activation makes the network expressive.',visualType:'interactive_simulation',visualData:{neuralMode:'m1'},tryThis:'Trace x₁ and x₂ into the weighted sum and predict whether increasing a weight will raise the output.'},
 {id:'m2_forward_loss',stepNumber:2,stage:'show',title:'M2 · Forward Pass + Loss',subtitle:'Prediction → target → error',buddyDialogue:'Connect neurons into a network. First the signal moves forward; then the loss tells us how far the prediction is from the target.',buddyState:'EXPLAINING',boardTitle:'From Input to Error',boardSummary:'Follow a small network forward, then compare its prediction with the target.',keyPrinciple:'Forward propagation produces the prediction; a loss function turns the prediction error into a number the network can learn from.',visualType:'interactive_simulation',visualData:{neuralMode:'m3'},tryThis:'Run the forward pass and decide which change would reduce the loss.'},
 {id:'m3_backprop_gradient',stepNumber:3,stage:'show',title:'M3 · Backprop + Gradients',subtitle:'Error backward → parameter updates',buddyDialogue:'Now send the error backward. Gradients show how each parameter contributed, giving the optimizer a direction to move.',buddyState:'EXPLAINING',boardTitle:'The Learning Signal Travels Backward',boardSummary:'Watch gradients flow from the loss back through the network.',keyPrinciple:'Backpropagation computes gradients efficiently; gradient descent uses them to change parameters.',visualType:'interactive_simulation',visualData:{neuralMode:'m5'},tryThis:'Follow the reverse path from the output error to an earlier weight.'},
 {id:'m4_gradient_descent',stepNumber:4,stage:'practice',title:'M4 · Gradient Descent',subtitle:'Step toward lower loss',buddyDialogue:'A gradient points toward increasing loss, so training moves in the opposite direction. The learning rate controls the step size.',buddyState:'ENCOURAGING',boardTitle:'Walk Down the Loss Landscape',boardSummary:'Visualize an update as the parameter moves toward a lower-loss region.',keyPrinciple:'θ ← θ − η∂L/∂θ; smaller loss is the training objective.',visualType:'interactive_simulation',visualData:{neuralMode:'m6'},tryThis:'Run one update and watch the parameter move toward lower loss.'},
 {id:'m5_deep_networks',stepNumber:5,stage:'show',title:'M5 · Deep Networks',subtitle:'Stack representations',buddyDialogue:'Add layers and the network can build richer representations: simple patterns first, then combinations of those patterns.',buddyState:'EXPLAINING',boardTitle:'Why Depth Matters',boardSummary:'Compare shallow and deep stacks of learned transformations.',keyPrinciple:'Depth creates successive representations rather than simply adding isolated neurons.',visualType:'interactive_simulation',visualData:{neuralMode:'m7'},tryThis:'Add a hidden layer and notice the extra transformation.'},
 {id:'m6_attention',stepNumber:6,stage:'show',title:'M6 · Self-Attention',subtitle:'Tokens use context',buddyDialogue:'Attention lets one token compare itself with the rest of the sequence and focus on the information that matters for its current context.',buddyState:'EXPLAINING',boardTitle:'Watch Tokens Share Context',boardSummary:'Select a token and see the attention relationship change.',keyPrinciple:'Query-key similarity produces weights that mix value information into a contextual representation.',visualType:'interactive_simulation',visualData:{neuralMode:'m8'},tryThis:'Select different tokens and watch which context relationship is emphasized.'},
 {id:'m7_transformer_parts',stepNumber:7,stage:'show',title:'M7 · Multi-Head + Position',subtitle:'Parallel relationships + token order',buddyDialogue:'Different attention heads can inspect different relationships, while positional encoding tells the model where each token sits in the sequence.',buddyState:'EXPLAINING',boardTitle:'Multiple Views of Context',boardSummary:'Compare attention heads and change the positional vector.',keyPrinciple:'Multi-head attention combines several relationship patterns and positional information exposes sequence order.',visualType:'interactive_simulation',visualData:{neuralMode:'m9'},tryThis:'Switch positions and compare the positional encoding.'},
 {id:'m8_transformer_prediction',stepNumber:8,stage:'practice',title:'M8 · Transformer Block + Next Token',subtitle:'Attention → residual → norm → FFN → prediction',buddyDialogue:'Put it together: a transformer block refines context, then a language model turns the final representation into probabilities for the next token.',buddyState:'EXPLAINING',boardTitle:'From Context to the Next Token',boardSummary:'See the transformer block and the final prediction pipeline in one visual.',keyPrinciple:'Transformers repeatedly refine representations; the final language-model head converts the representation into a vocabulary distribution.',visualType:'interactive_simulation',visualData:{neuralMode:'m10'},tryThis:'Read the block left to right, then predict which token should have the highest probability.'},
 {id:'q1_final_check',stepNumber:9,stage:'challenge',title:'Q9 · Final Decision Tree Check',subtitle:'Prove the whole path',buddyDialogue:'You have seen the complete path from one neuron to a transformer prediction. Now prove that you can connect the ideas without another teaching prompt.',buddyState:'THINKING',boardTitle:'Final Check · Choose the Correct Learning Path',boardSummary:'Use the decision tree, answer the check, and your result becomes the signal for the next neural-network topic.',keyPrinciple:'A neural network learns by predicting, measuring loss, computing gradients, and updating parameters; transformers extend this with contextual attention.',visualType:'interactive_simulation',visualData:{neuralMode:'q1'},checkQuestion:{id:'nn_final_check',prompt:'Which sequence best describes how the taught neural-network system learns and then uses context?',options:[{id:'correct',text:'Forward prediction → loss → backprop gradients → update weights → attention/transformer builds context',isCorrect:true,feedback:'Correct. You connected training mechanics with the contextual representation used by transformer-style models.'},{id:'wrong1',text:'Randomly change weights → choose a token → calculate loss afterward',isCorrect:false,feedback:'Training is driven by a defined loss and gradients, not random weight changes.'},{id:'wrong2',text:'Attention happens first → weights never change → prediction is fixed',isCorrect:false,feedback:'Attention is part of the forward computation; learning still updates parameters from gradients.'}]}}
 ]],
 questions:[],flashcards:[],sources:[
 {id:'nn_src_1',title:'Deep Learning',authorOrPublisher:'Goodfellow, Bengio & Courville',type:'textbook',note:'Reference for neural networks and deep learning.'},
 {id:'nn_src_2',title:'Attention Is All You Need',authorOrPublisher:'Vaswani et al.',type:'paper',url:'https://arxiv.org/abs/1706.03762',note:'Reference for self-attention and positional encoding.'}
 ],
 buddyScript:{introduction:'We will build the idea from one neuron to token prediction, one calculation at a time.',correct:'Correct. Keep following the numbers.',incorrect:'Not quite. Trace the current operation on the Smart Board.',hint:'Inspect the highlighted calculation on the board.',transition:'Good. Move to the next transformation.',completion:'You traced the full path from a neuron to token prediction.'},
 xiraPrompts:{why:'Explain why this neural-network step works.',simpler:'Explain the current neural-network operation more simply.',example:'Give a concrete numerical example for this step.',hint:'Give me one small hint without revealing the answer.',deeper:'Connect this step to modern AI systems.'}
};