/**
 * Xpedition Learning Object Design System — Core Types
 *
 * Physical, creative learning materials:
 * 1. Flashcards (playing-card / collectible study card)
 * 2. Formula Cards (scientific letterpress index cards)
 * 3. Sticky Notes (tactile Post-it notes with handwritten typography)
 *
 * ARCHITECTURAL PRINCIPLE:
 * CONTENT is strictly separated from DESIGN.
 * The visual shells are FIXED.
 * Content is completely data-driven and can be generated by Xira or any source.
 */

export type SubjectCategory =
  | 'physics'
  | 'mathematics'
  | 'chemistry'
  | 'biology'
  | 'programming'
  | 'general';

// ============================================================================
// 1. FLASHCARD TYPES
// ============================================================================

export type FlashcardColorTheme =
  | 'navy'       // #0B2952 (e.g. DC Motor)
  | 'forest'     // #0F3D26 (e.g. Magnetic Force)
  | 'terracotta' // #823419 (e.g. Quick Check / Commutation)
  | 'amber'      // #8A5B14
  | 'slate'      // #1E293B
  | 'violet';    // #3B185F

export type FlashcardEmblem =
  | 'lightning'
  | 'magnet'
  | 'question'
  | 'gear'
  | 'atom'
  | 'sparkle'
  | 'compass';

export interface FlashcardContent {
  id: string;
  subject?: string;              // e.g. "PHYSICS"
  cardNumber?: string;           // e.g. "01", "02"
  title: string;                 // e.g. "DC MOTOR"
  colorTheme?: FlashcardColorTheme;
  emblem?: FlashcardEmblem;
  illustrationUrl?: string;      // 3D realistic cutout render
  illustrationAlt?: string;
  front: {
    question: string;            // e.g. "What happens when current direction reverses?"
    answerPreview?: string;      // e.g. "The motor's rotation reverses."
  };
  back: {
    answer: string;              // Primary crisp answer
    explanation?: string;        // In-depth physical mechanism
    keyTakeaway?: string;        // Bullet/rule to remember
    formulaSnippet?: string;     // Associated equation if any
  };
  conceptId?: string;
  tags?: string[];
  status?: 'UNSEEN' | 'KNOWN' | 'REVIEW';
  rotation?: number;             // e.g. -1.5, 1, 0 (degrees)
}

// ============================================================================
// 2. FORMULA CARD TYPES
// ============================================================================

export interface FormulaVariable {
  symbol: string;                // e.g. "F", "I", "L", "\theta"
  description: string;           // e.g. "Force", "Current"
  unit?: string;                 // e.g. "N", "A", "m", "T"
}

export interface FormulaCardContent {
  id: string;
  subject: string;               // e.g. "PHYSICS"
  cardNumber?: string;           // e.g. "FORMULA CARD 01"
  title: string;                 // e.g. "MAGNETIC FORCE"
  formulaTex: string;            // e.g. "F = I \\cdot L \\cdot B \\cdot \\sin(\\theta)"
  variables: FormulaVariable[];
  unit?: string;                 // Resulting unit, e.g. "Newtons (N)"
  example?: string;              // Worked example or physical interpretation
  emblem?: 'atom' | 'magnet' | 'math' | 'compass' | 'gear' | 'delta';
  conceptId?: string;
  note?: string;
  rotation?: number;             // e.g. -1, 1.5, 0 (degrees)
}

// ============================================================================
// 3. STICKY NOTE TYPES
// ============================================================================

export type StickyNoteType =
  | 'key_idea'
  | 'remember'
  | 'try_this'
  | 'common_mistake'
  | 'hint'
  | 'question'
  | 'example'
  | 'think_about_this';

export type StickyNoteColor =
  | 'yellow'     // Warm yellow (#FFF7A1)
  | 'green'      // Pale green (#D4F7D4)
  | 'blue'       // Soft blue (#C9E8FF)
  | 'pink'       // Coral/pink (#FFD1DC)
  | 'orange'     // Amber/orange (#FFE0B2)
  | 'lavender';  // Soft lavender (#E8D7FF)

export interface StickyNoteContent {
  id: string;
  type: StickyNoteType;
  color?: StickyNoteColor;
  title?: string;                // e.g. "KEY IDEA", "REMEMBER", "COMMON MISTAKE"
  content: string;               // Handwritten script content
  author?: string;               // e.g. "Buddy", "Student", "Xira"
  rotation?: number;             // e.g. -2.5, 1.8, 3.2 (degrees)
  conceptId?: string;
  timestamp?: number;
}
